services: 
  skillSync_db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: skillSync_db
      MYSQL_USER: skillSync_user
      MYSQL_PASSWORD: dfghj
    ports:
      - "3307:3306"
    volumes:
      - skillSync_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pqwerty"]
      interval: 10s
      timeout: 5s
      retries: 10


  app:
    image: aineshsridhar/synergy-platform-app:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      skillSync_db:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for MySQL to be ready...' &&
        until mysqladmin ping -h skillSync_db -u root -pqwerty --silent; do
          sleep 2;
        done &&
        echo 'Running Prisma migrations...' &&
        npx prisma migrate deploy &&
        echo 'Starting app...' &&
        npm start
      "

volumes:
  skillSync_mysql_data:
