import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar";
import { UserContextProvider } from "../components/UserContextProvider";
import { getUserFromSession } from "@/utils/auth";

// Geist Sans (variable font)
const geistSans = localFont({
  src: "../../public/fonts/Geist/Geist-VariableFont_wght.ttf",
  variable: "--font-geist-sans",
});

// Geist Mono (variable font)
const geistMono = localFont({
  src: "../../public/fonts/GeistMono/GeistMono-VariableFont_wght.ttf",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserFromSession();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserContextProvider user={user}>
          <Navbar />
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
